name: sql_query_manager
description: Sql Query generator for Dart.
version: 1.0.0
homepage: https://github.com/Flerma98
repository: https://github.com/Flerma98/sql_query_manager
issue_tracker: https://github.com/Flerma98/sql_query_manager

environment:
  sdk: ^3.3.3

dependencies:
  intl: ^0.19.0
  sqflite: ^2.3.3
  sqflite_common: ^2.5.4


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  sqflite_common_ffi: ^2.3.3
